name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Tai va cai dat ngrok
        run: |
          choco install ngrok -y
      - name: Cau hinh ngrok token
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Bat RDP tren Windows Runner
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
      - name: Tao mat khau cho tai khoan RunnerAdmin
        run: |
          net user RunnerAdmin Ent$56gh56434343434
      - name: Khoi tao duong truyen RDP
        run: |
          Start-Process Powershell -ArgumentList '-NoExit', '-Command', 'ngrok tcp 3389'
      - name: Lay thong tin ket noi RDP
        run: |
          Start-Sleep -Seconds 5
          Invoke-RestMethod -Uri http://localhost:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Select-Object -ExpandProperty public_url
      - name: Duy tri phien lam viec
        run: |
          $i = 0
          while ($i -lt 350) {
            Start-Sleep -Seconds 60
            $i++
          }
        
